import { createRef } from 'react';

const data = [
	{
		key: 1,
		date: '8 Aug',
		ref: createRef(),
		matches: [
			{
				key: 1,
				team1: 'Man Utd',
				team2: 'FC Barcelona',
				time: '8:00pm',
				logo1: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/237px-Manchester_United_FC_crest.svg.png',
				logo2: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/142px-FC_Barcelona_%28crest%29.svg.png',
				ref: createRef(),
			},
			{
				key: 2,
				team1: 'Man City',
				team2: 'Man Utd',
				time: '9:00pm',
				logo1: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/240px-Manchester_City_FC_badge.svg.png',
				logo2: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/237px-Manchester_United_FC_crest.svg.png',
				ref: createRef(),
			},
			{
				key: 3,
				team1: 'Man City',
				team2: 'FC Barcelona',
				time: '10:00pm',
				logo1: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/240px-Manchester_City_FC_badge.svg.png',
				logo2: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/142px-FC_Barcelona_%28crest%29.svg.png',
				ref: createRef(),
			},
			{
				key: 4,
				team1: 'Man Utd',
				team2: 'Man City',
				time: '12:00pm',
				logo1: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/237px-Manchester_United_FC_crest.svg.png',
				logo2: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/240px-Manchester_City_FC_badge.svg.png',
				ref: createRef(),
			},
			{
				key: 5,
				team1: 'Man Utd',
				team2: 'Chelsea',
				time: '12:00pm',
				logo1: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/237px-Manchester_United_FC_crest.svg.png',
				logo2: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/240px-Chelsea_FC.svg.png',
				ref: createRef(),
			},
			{
				key: 6,
				team1: 'Real Madrid',
				team2: 'Man City',
				time: '12:00pm',
				logo1: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/179px-Real_Madrid_CF.svg.png',
				logo2: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/240px-Manchester_City_FC_badge.svg.png',
				ref: createRef(),
			},
		],
	},
	{
		key: 2,
		date: '15 Oct',
		ref: createRef(),
		matches: [
			{
				key: 1,
				team1: 'Man Utd',
				team2: 'Real Madrid',
				time: '5:00pm',
				logo1: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/237px-Manchester_United_FC_crest.svg.png',
				logo2: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/179px-Real_Madrid_CF.svg.png',
				ref: createRef(),
			},
			{
				key: 2,
				team1: 'Man City',
				team2: 'Real Madrid',
				time: '7:00pm',
				logo1: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/240px-Manchester_City_FC_badge.svg.png',
				logo2: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/179px-Real_Madrid_CF.svg.png',
				ref: createRef(),
			},
			{
				key: 3,
				team1: 'Real Madrid',
				team2: 'FC Barcelona',
				time: '9:00pm',
				logo1: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/179px-Real_Madrid_CF.svg.png',
				logo2: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/142px-FC_Barcelona_%28crest%29.svg.png',
				ref: createRef(),
			},
			{
				key: 4,
				team1: 'Man Utd',
				team2: 'Man City',
				time: '11:00pm',
				logo1: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/237px-Manchester_United_FC_crest.svg.png',
				logo2: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/240px-Manchester_City_FC_badge.svg.png',
				ref: createRef(),
			},
		],
	},
	{
		key: 3,
		date: '27 Dec',
		ref: createRef(),
		matches: [
			{
				key: 1,
				team1: 'Real Madrid',
				team2: 'FC Barcelona',
				time: '1:00am',
				logo1: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/179px-Real_Madrid_CF.svg.png',
				logo2: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/142px-FC_Barcelona_%28crest%29.svg.png',
				ref: createRef(),
			},
			{
				key: 2,
				team1: 'Man City',
				team2: 'Man Utd',
				time: '2:00pm',
				logo1: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/240px-Manchester_City_FC_badge.svg.png',
				logo2: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/237px-Manchester_United_FC_crest.svg.png',
				ref: createRef(),
			},
			{
				key: 3,
				team1: 'Chelsea',
				team2: 'FC Barcelona',
				time: '5:00pm',
				logo1: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/240px-Chelsea_FC.svg.png',
				logo2: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/47/FC_Barcelona_%28crest%29.svg/142px-FC_Barcelona_%28crest%29.svg.png',
				ref: createRef(),
			},
			{
				key: 4,
				team1: 'Chelsea',
				team2: 'Real Madrid',
				time: '10:00pm',
				logo1: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/240px-Chelsea_FC.svg.png',
				logo2: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Real_Madrid_CF.svg/179px-Real_Madrid_CF.svg.png',
				ref: createRef(),
			},
		],
	},
];

export default data;
